# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(ci)"
    labels:
      - "dependency-actions"
    open-pull-requests-limit: 50

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependency-nuget"
    open-pull-requests-limit: 50
    groups:
      ms-extensions:
        patterns:
          - "Microsoft.Extensions*"
      fluentassertions:
        patterns:
          - "FluentAssertions"
      else:
        patterns:
          - "*"
    
